[package]
name = "voter-define"
version = "0.1.0"
edition = "2018"
authors = ["Shogo Murakami <shogo.murakami@broadleaf.co.jp>"]

[dependencies]
casper-contract = "=1.4.1"
casper-types = "=1.4.1"

[[bin]]
name = "voter-define"
path = "src/main.rs"
bench = false
doctest = false
test = false